Repository GDSC-Popcorn/Popcorn-iOS, pull requests merged in 2024-11, with the labels that each got.

#4 [Chore] CI 환경 구축
  .github:workflows/build_test_on_develop.yml
  Popcorn-iOS.xcodeproj/xcshareddata/xcschemes/Popcorn-iOS.xcscheme
  Popcorn-iOSTests/Popcorn_iOSTests.swift
Labels: ⚙️ SetUp

#7 [Feat] 메인화면의 캐러셀 컴포넌트를 구현하였습니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Presentation/Main/Common/View/MainCellPagingCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/Main/Common/View/MainCellPagingImageView.swift
  Popcorn-iOS/Source/Presentation/Main/Common/ViewModel/MainCellPagingViewModel.swift
  Popcorn-iOS/Source/Util/Reusable.swift
Labels: 🎨 Feature

#62 [Feat] 로그인화면의 UI를 구현했습니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Resource/Assets.xcassets/login_apple.imageset/Contents.json
  Popcorn-iOS/Resource/Assets.xcassets/login_apple.imageset/Image.png
  Popcorn-iOS/Resource/Assets.xcassets/login_apple.imageset/Image@2x.png
  Popcorn-iOS/Resource/Assets.xcassets/login_apple.imageset/Image@3x.png
  Popcorn-iOS/Resource/Assets.xcassets/login_google.imageset/Contents.json
  Popcorn-iOS/Resource/Assets.xcassets/login_google.imageset/Image.png
  Popcorn-iOS/Resource/Assets.xcassets/login_google.imageset/Image@2x.png
  Popcorn-iOS/Resource/Assets.xcassets/login_google.imageset/Image@3x.png
  Popcorn-iOS/Resource/Assets.xcassets/login_kakao.imageset/Contents.json
  Popcorn-iOS/Resource/Assets.xcassets/login_kakao.imageset/Image.png
  Popcorn-iOS/Resource/Assets.xcassets/login_kakao.imageset/Image@2x.png
  Popcorn-iOS/Resource/Assets.xcassets/login_kakao.imageset/Image@3x.png
  Popcorn-iOS/Resource/Assets.xcassets/login_popcorn.imageset/Contents.json
  Popcorn-iOS/Resource/Assets.xcassets/login_popcorn.imageset/로고 (1).png
  Popcorn-iOS/Resource/Assets.xcassets/login_popcorn.imageset/로고 (2).png
  Popcorn-iOS/Resource/Assets.xcassets/login_popcorn.imageset/로고.png
  Popcorn-iOS/Source/Presentation/Login/Common/View/LoginTextField.swift
  Popcorn-iOS/Source/Presentation/Login/LoginScene/Controller/LoginViewController.swift
  Popcorn-iOS/Source/Presentation/Login/LoginScene/View/LoginView.swift
Labels: 🎨 Feature

#64 [Feat] 메인화면의 UI와 뷰 모델을 구현합니다
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Domain/Model/Entities/PopupPreview.swift
  Popcorn-iOS/Source/Domain/Model/Entities/UserInterestPopup.swift
  Popcorn-iOS/Source/Presentation/Main/Common/View/MainCellPagingCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/Main/Common/View/MainCellPagingImageView.swift
  Popcorn-iOS/Source/Presentation/Main/Common/ViewModel/MainCellPagingViewModel.swift
  Popcorn-iOS/Source/Presentation/Main/View/ClosingSoonPopupCell.swift
  Popcorn-iOS/Source/Presentation/Main/View/MainCollectionHeaderView.swift
  Popcorn-iOS/Source/Presentation/Main/View/MainSceneViewController.swift
  Popcorn-iOS/Source/Presentation/Main/View/PickOrInterestCell.swift
  Popcorn-iOS/Source/Presentation/Main/ViewModel/MainSceneViewModel.swift
  Popcorn-iOS/Source/Util/Extensions/Date+.swift
  Popcorn-iOS/Source/Util/Extensions/UIView+.swift
  Popcorn-iOS/Source/Util/Reusable.swift
Labels: 🎨 Feature

#69 [Refactor] 디자인 시스템 적용
  Popcorn-iOS/Source/Presentation/Main/Common/View/MainCellPagingCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/Main/Common/View/MainCellPagingImageView.swift
  Popcorn-iOS/Source/Presentation/Main/View/ClosingSoonPopupCell.swift
  Popcorn-iOS/Source/Presentation/Main/View/MainCollectionHeaderView.swift
  Popcorn-iOS/Source/Presentation/Main/View/MainSceneViewController.swift
  Popcorn-iOS/Source/Presentation/Main/View/PickOrInterestCell.swift
  Popcorn-iOS/Source/Presentation/Main/ViewModel/MainSceneViewModel.swift
Labels: 👨‍🏭 Refactor
