Repository GDSC-Popcorn/Popcorn-iOS, pull requests merged in 2025-02, with the labels that each got.

#89 Rename: 클린아키텍처에 맞춰 폴더 구조를 변경합니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Data/Repositories/LoginRepository.swift
  Popcorn-iOS/Source/Data/Repositories/SocialLoginRepository.swift
  Popcorn-iOS/Source/Data/Repositories/TokenRepository.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupInformation.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupPreview.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/UserInterestPopup.swift
  Popcorn-iOS/Source/Domain/Entities/Token/NewToken.swift
  Popcorn-iOS/Source/Domain/Entities/Token/Token.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/Login/LoginRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/Login/SocialLoginRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/Token/TokenRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/UseCases/LoginUseCase/LoginUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/LoginUseCase/SocialLoginUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/TokenUseCase/TokenUseCase.swift
  Popcorn-iOS/Source/Presentation/MainScene/Common/View/MainCarouselCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/Common/View/MainCarouselView.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/MainSceneViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/ReusableView/ClosingSoonPopupCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/ReusableView/MainCarouselPickHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/ReusableView/MainCollectionHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/ReusableView/MainCollectionTitleHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/ReusableView/PickOrInterestCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/FullScreenReviewImageViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/PopupDetailViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/RatingDistributionView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/CarouselHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/PopupDetailInfoCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/PopupInfoReviewSegmentHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/PopupRatingCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/PopupTitleCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/ReviewCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/ReviewImageCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/ReviewSortButtonHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/UploadImageCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/StarRatingView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/WriteReviewViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/Protocol/Delegate/ReviewCollectionViewCellDelegate.swift
  Popcorn-iOS/Source/Presentation/MainScene/Protocol/Delegate/StarRatingViewDelegate.swift
  Popcorn-iOS/Source/Presentation/MainScene/Protocol/Delegate/WriteReviewButtonDelegate.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/MainCarouselViewModelProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/MainSceneViewModel.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/PopupDetailViewModel.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/WriteReviewViewModel.swift
Labels: 👨‍🏭 Refactor

#90 [Feat] Image 로드 객체를 레이어별로 구현합니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Data/Network/ImageFetchManager/ImageFetchError.swift
  Popcorn-iOS/Source/Data/Network/ImageFetchManager/ImageFetchManager.swift
  Popcorn-iOS/Source/Data/Network/ImageFetchManager/ImageFetchManagerProtocol.swift
  Popcorn-iOS/Source/Data/Repositories/ImageFetchManagerRepository.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/ImageFetchManager/ImageFetchManagerRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/UseCases/ImageFetchUseCase/Implementations/ImageFetchUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/ImageFetchUseCase/Interfaces/ImageFetchUseCaseProtocol.swift
Labels: 🎨 Feature

#92 [Feat] 메인화면에 들어갈 때 서버에서 데이터를 받아올 수 있도록 합니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Data/DTO/MainScene/PopupMainListResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/PopupPreviewResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/TodayRecommendPopupsResponseDTO.swift
  Popcorn-iOS/Source/Data/Network/ImageFetchManager/ImageFetchManager.swift
  Popcorn-iOS/Source/Data/Network/NetworkManager/NetworkManager.swift
  Popcorn-iOS/Source/Data/Repositories/ImageFetchManagerRepository.swift
  Popcorn-iOS/Source/Data/Repositories/MainScene/PopupListRepository.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupInformation.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupMainList.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupPreview.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/UserInterestPopup.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/MainScene/PopupListRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/UseCases/ImageFetchUseCase/Implementations/ImageFetchUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Implementations/FetchPopupListUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Interfaces/FetchPopupListUseCaseProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/Common/Util/PopupDateFormatter.swift
  Popcorn-iOS/Source/Presentation/MainScene/Common/View/MainCarouselView.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/MainSceneViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/PopupDetailViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/Protocol/MainCarouselViewModelProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/MainCarouselViewModelProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/MainSceneViewModel.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/PopupDetailViewModel.swift
Labels: 🎨 Feature, 👨‍🏭 Refactor

#93 [Feat] 카카오톡 로그인 시 신규 유저 여부 판단 및 회원가입/메인 화면 이동 로직을 추가하였습니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Application/SceneDelegate.swift
  Popcorn-iOS/Source/Data/DTO/Login/LoginResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/Login/ReissueResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/Login/Request/LoginRequestDTO.swift
  Popcorn-iOS/Source/Data/DTO/Login/Request/SocialLoginRequestDTO.swift
  Popcorn-iOS/Source/Data/DTO/Login/Response/SocialLoginResponseDTO.swift
  Popcorn-iOS/Source/Data/Network/APIConstant.swift
  Popcorn-iOS/Source/Data/Repositories/Login/SocialLoginRepository.swift
  Popcorn-iOS/Source/Data/Repositories/Token/TokenRepository.swift
  Popcorn-iOS/Source/Domain/Entities/Token/IdToken.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/Login/SocialLoginRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/Token/TokenRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/UseCases/LoginUseCase/SocialLoginUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/TokenUseCase/TokenUseCase.swift
  Popcorn-iOS/Source/Presentation/Login/LoginScene/ViewModels/SocialLoginViewModel.swift
  Popcorn-iOS/Source/Presentation/Login/LoginScene/Views/LoginViewController.swift
Labels: 🎨 Feature

#94 [Feat] 메인화면의 프레젠테이션 레이어를 리팩토링 합니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Data/DTO/MainScene/TodayRecommendPopupsResponseDTO.swift
  Popcorn-iOS/Source/Data/Repositories/MainScene/PopupListRepository.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupMainList.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Implementations/PopupFetchListUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Interfaces/PopupFetchListUseCaseProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/Common/Util/PopupDateFormatter.swift
  Popcorn-iOS/Source/Presentation/MainScene/Common/View/MainCarouselView.swift
  Popcorn-iOS/Source/Presentation/MainScene/DataSource/MainSceneDataSource.swift
  Popcorn-iOS/Source/Presentation/MainScene/DataSource/PopupDetailDataSource.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/MainSceneViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/ReusableView/MainCarouselPickHeaderView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/PopupDetailViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/Protocol/MainCarouselViewModelProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/MainSceneViewModel.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/PopupDetailViewModel.swift
Labels: 👨‍🏭 Refactor

#96 상세화면 입장 시 서버에서 데이터를 받아올 수 있도록 합니다.
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Source/Application/AppDelegate.swift
  Popcorn-iOS/Source/Application/SceneDelegate.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/MainScene/PopupMainListResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/MainScene/PopupPreviewResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/PopupDetailScene/PopupInformationResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/PopupDetailScene/PopupRatingDistributionResponseDTO.swift
  Popcorn-iOS/Source/Data/DTO/MainScene/PopupDetailScene/PopupReviewListResponseDTO.swift
  Popcorn-iOS/Source/Data/Network/APIConstant.swift
  Popcorn-iOS/Source/Data/Repositories/ImageFetchManagerRepository.swift
  Popcorn-iOS/Source/Data/Repositories/MainScene/PopupDetailRepository.swift
  Popcorn-iOS/Source/Data/Repositories/MainScene/PopupListRepository.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/MainScene/MainScene/PopupMainList.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/MainScene/MainScene/PopupPreview.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/MainScene/MainScene/UserInterestPopup.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/MainScene/PopupDetailScene/PopupInformation.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/MainScene/PopupDetailScene/PopupRating.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/MainScene/PopupDetailScene/PopupReviewList.swift
  Popcorn-iOS/Source/Domain/Entities/MainScene/PopupInformation.swift
  Popcorn-iOS/Source/Domain/Interfaces/Repositories/MainScene/PopupDetailRepositoryProtocol.swift
  Popcorn-iOS/Source/Domain/UseCases/ImageFetchUseCase/Implementations/ImageFetchUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Implementations/PopupDetailUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Implementations/PopupFetchListUseCase.swift
  Popcorn-iOS/Source/Domain/UseCases/MainScene/Interfaces/PopupDetailUseCaseProtocol.swift
  Popcorn-iOS/Source/Presentation/Login/LoginScene/Views/LoginViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/DataSource/MainSceneDataSource.swift
  Popcorn-iOS/Source/Presentation/MainScene/DataSource/PopupDetailDataSource.swift
  Popcorn-iOS/Source/Presentation/MainScene/MainSceneView/MainSceneViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/PopupDetailViewController.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/RatingDistributionView.swift
  Popcorn-iOS/Source/Presentation/MainScene/PopupDetailView/ReusableView/PopupRatingCollectionViewCell.swift
  Popcorn-iOS/Source/Presentation/MainScene/Protocol/MainCarouselViewModelProtocol.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/MainSceneViewModel.swift
  Popcorn-iOS/Source/Presentation/MainScene/ViewModel/PopupDetailViewModel.swift
  Popcorn-iOSTests/MainScene/DetailSceneUseCaseTests.swift
  Popcorn-iOSTests/Popcorn_iOSTests.swift
  Popcorn-iOSTests/TestDouble/Dummy/DummyPopupDetailRepository.swift
Labels: 🎨 Feature

#97 Bundle Identifier 수정 및 인증서 추가
  Popcorn-iOS.xcodeproj/project.pbxproj
  Popcorn-iOS/Popcorn-iOS.entitlements
  ios_development.cer
Labels: ⚙️ SetUp
